Repository binarybarnyard/gamejam15, pull requests merged in 2024-07, with the labels that each got.

#2 Initial Enemy + Enemy States
  Assets/Tilesets/metal_snow_tileset.tres
  Scenes/MainScene.tscn
  Scenes/Player.tscn
  Scenes/Slime.tscn
  Scenes/StateMachines/GroundEnemyStateMachine.tscn
  Scenes/StateMachines/PlayerStateMachine.tscn
  Scripts/Enemies/GroundEnemy.cs
  Scripts/Enemies/Slime.cs
  Scripts/Enemies/States/GroundChase.cs
  Scripts/Enemies/States/GroundDead.cs
  Scripts/Enemies/States/GroundHit.cs
  Scripts/Enemies/States/GroundIdle.cs
  Scripts/Enemies/States/GroundWander.cs
  Scripts/Player/Player.cs
  Scripts/Player/States/PlayerAttack.cs
Labels: enhancement

#3 States bugfix
  Scripts/Enemies/States/GroundChase.cs
  Scripts/Player/Player.cs
  Scripts/Player/States/PlayerAttack.cs
  Scripts/Player/States/PlayerDead.cs
  Scripts/Player/States/PlayerFall.cs
  Scripts/Player/States/PlayerIdle.cs
  project.godot
Labels: bug

#4 UI
  Assets/Tilesets/metal_snow_tileset.tres
  Assets/fonts/Pixel_NES.otf
  Assets/sprites/Traders/craftpix-net-922426-free-city-trader-character-sprite-sheets-pixel-art.zip
  Assets/sprites/Traders/craftpix-net-922426-free-city-trader-character-sprite-sheets-pixel-art/COUPON.pdf
  Assets/sprites/Traders/craftpix-net-922426-free-city-trader-character-sprite-sheets-pixel-art/COUPON.png
  Assets/sprites/Traders/craftpix-net-922426-free-city-trader-character-sprite-sheets-pixel-art/Font.txt
  Assets/sprites/Traders/craftpix-net-922426-free-city-trader-character-sprite-sheets-pixel-art/Free Assets Craftpix!.url
  Assets/sprites/Traders/craftpix-net-922426-free-city-trader-character-sprite-sheets-pixel-art/Licens.txt
  Assets/sprites/Traders/craftpix-net-922426-free-city-trader-character-sprite-sheets-pixel-art/PSD/NPC_1_Spritelist.psd
  Assets/sprites/Traders/craftpix-net-922426-free-city-trader-character-sprite-sheets-pixel-art/PSD/NPC_2_Spritelist.psd
  Assets/sprites/Traders/craftpix-net-922426-free-city-trader-character-sprite-sheets-pixel-art/PSD/NPC_3_Spritelist.psd
  Assets/sprites/Traders/craftpix-net-922426-free-city-trader-character-sprite-sheets-pixel-art/Trader_1/Approval.png
  Assets/sprites/Traders/craftpix-net-922426-free-city-trader-character-sprite-sheets-pixel-art/Trader_1/Dialogue.png
  Assets/sprites/Traders/craftpix-net-922426-free-city-trader-character-sprite-sheets-pixel-art/Trader_1/Idle.png
  Assets/sprites/Traders/craftpix-net-922426-free-city-trader-character-sprite-sheets-pixel-art/Trader_1/Idle_2.png
  Assets/sprites/Traders/craftpix-net-922426-free-city-trader-character-sprite-sheets-pixel-art/Trader_1/Idle_3.png
  Assets/sprites/Traders/craftpix-net-922426-free-city-trader-character-sprite-sheets-pixel-art/Trader_2/Approval.png
  Assets/sprites/Traders/craftpix-net-922426-free-city-trader-character-sprite-sheets-pixel-art/Trader_2/Dialogue.png
  Assets/sprites/Traders/craftpix-net-922426-free-city-trader-character-sprite-sheets-pixel-art/Trader_2/Idle.png
  Assets/sprites/Traders/craftpix-net-922426-free-city-trader-character-sprite-sheets-pixel-art/Trader_2/Idle_2.png
  Assets/sprites/Traders/craftpix-net-922426-free-city-trader-character-sprite-sheets-pixel-art/Trader_2/Idle_3.png
  Assets/sprites/Traders/craftpix-net-922426-free-city-trader-character-sprite-sheets-pixel-art/Trader_3/Approval.png
  Assets/sprites/Traders/craftpix-net-922426-free-city-trader-character-sprite-sheets-pixel-art/Trader_3/Dialogue.png
  Assets/sprites/Traders/craftpix-net-922426-free-city-trader-character-sprite-sheets-pixel-art/Trader_3/Idle.png
  Assets/sprites/Traders/craftpix-net-922426-free-city-trader-character-sprite-sheets-pixel-art/Trader_3/Idle_2.png
  Assets/sprites/Traders/craftpix-net-922426-free-city-trader-character-sprite-sheets-pixel-art/Trader_3/Idle_3.png
  Scenes/MainScene.tscn
  Scenes/NPCs/Pops.tscn
  Scenes/Player.tscn
  Scenes/Timers/GlobalTick.tscn
  Scenes/UI/Dialog/DialogManager.tscn
  Scenes/UI/Themes/DialogManager.tres
  Scripts/Classes/CharacterBody.cs
  Scripts/Classes/DialogManager.cs
  Scripts/Classes/Utilities/SettingsFetcher.cs
  Scripts/Enemies/GroundEnemy.cs
  Scripts/InterFaces/ICharacter.cs
  Scripts/Interface/CharacterScreen.cs
  Scripts/Interface/UI.cs
  Scripts/NPCs/Pops.cs
  Scripts/Player/Player.cs
  Scripts/Player/States/PlayerHit.cs
  Scripts/Player/States/PlayerJump.cs
  project.godot
Labels: enhancement

#9 Shadow Enemy + Bugfix
  Scenes/Enemies/Shadow.tscn
  Scenes/Environment/Lantern.tscn
  Scenes/MainScene.tscn
  Scenes/Player.tscn
  Scenes/StateMachines/ShadowStateMachine.tscn
  Scripts/Classes/CharacterBody.cs
  Scripts/Classes/DialogManager.cs
  Scripts/Classes/GroundEnemy.cs
  Scripts/Classes/Interface/Dialog/DialogArea.cs
  Scripts/Enemies/Shadow.cs
  Scripts/Enemies/States/ShadowChase.cs
  Scripts/Enemies/States/ShadowDead.cs
  Scripts/Enemies/States/ShadowSpawn.cs
  Scripts/NPCs/Pops.cs
  Scripts/Player/States/PlayerAttack.cs
  Scripts/Player/States/PlayerMove.cs
Labels: bug, enhancement
